title: "chwast.it"
subtitle: "najgorszy podcast programistyczny"
email: "peel+podcast@coderasonist.com"
repo: "peel/podcast"
description: > 
  Najgorszy podcast programistyczny w Polsce.  
  Niezobowiązująco, nieznośnie i prawdopodobnie lekceważąco o szeroko pojętej inżynierii oprogramowania opowiadają:  
  @kwasniew - wielki fan sieci Web i prostych (niekoniecznie popularnych) rozwiązań. Zwolennik odnajdywania oryginalnych problemów zamiast naprawiania symptomów. Programista, speaker, trener.  
  @kubek2k - pomysłodawca całego zamieszania. Developer praktykujący programistyczny szamanizm. Szczerze niewierzacy agilista. Ostatnio nie mamy z nim kontaktu, więc pewnie popełnia kolejny refactoring.  
  @peel - señor code arsonist. Praktyk, teoretyk i teolog programowania funkcyjnego. Speaker, maker, miłośnik poprawiania tych drobnych rzeczy, które irytują. Wróg złych rozwiązań. Prawdopodobnie nie raz mu się naraziliście. Czarownik evil-mode.   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chwast.codearsonist.com"
author: "chwast.it"
owner: "chwast.it"
explicit: no
album_art: "/img/albumart.jpg"
category: "Technology"
subcategory_one: "Software How-To"
subcategory_two: "Tech News"
itunes: https://itunes.apple.com/pl/podcast/chwast-it/id1303100860
stitcher: https://www.stitcher.com/podcast/chwastit
feed: https://feeds.feedburner.com/chwastit

google_analytics: UA-108807964-1

# Build settings
markdown: kramdown
permalink: /:title
theme: minima
# gems:
#   - jekyll-feed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - default.nix
  - gemset.nix
